# Deployment for config-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: config-server
      project: university-management
  template:
    metadata:
      labels:
        app: config-server
        project: university-management
    spec:
      containers:
        - name: config-server
          image: config-server:latest
          ports:
            - containerPort: 8888
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            livenessProbe:
              httpGet:
                path: /actuator/health
                port: 8080
              initialDelaySeconds: 10
              periodSeconds: 10

---

# Deployment for api-gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
      project: university-management
  template:
    metadata:
      labels:
        app: api-gateway
        project: university-management
    spec:
      containers:
        - name: api-gateway
          image: api-gateway:latest
          ports:
            - containerPort: 9090
          env:
            - name: STUDENT_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: university-management-secret
                  key: student_service_url
            - name: ADDRESS_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: university-management-secret
                  key: address_service_url

---

# Deployment for student-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-service
  labels:
    app: student-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-service
      project: university-management
  template:
    metadata:
      labels:
        app: student-service
        project: university-management
    spec:
      containers:
        - name: student-service
          image: student-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: university-management-secret
                  key: datasource_url
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: university-management-secret
                  key: datasource_username
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: university-management-secret
                  key: datasource_password
            - name: ADDRESS_SERVICE_URL_GATEWAY
              valueFrom:
                secretKeyRef:
                  name: university-management-secret
                  key: address_service_url_gateway
---

# Deployment for address-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: address-service
  labels:
    app: address-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: address-service
      project: university-management
  template:
    metadata:
      labels:
        app: address-service
        project: university-management
    spec:
      containers:
        - name: address-service
          image: address-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: university-management-secret
                  key: datasource_url
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: university-management-secret
                  key: datasource_username
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: university-management-secret
                  key: datasource_password
