# Deployment for config-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: config-server
      project: university-management
  template:
    metadata:
      labels:
        app: config-server
        project: university-management
    spec:
      containers:
        - name: config-server
          image: us-central1-docker.pkg.dev/university-management-476414/university-management/config-server:latest
          ports:
            - containerPort: 8888

---

# Deployment for api-gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
      project: university-management
  template:
    metadata:
      labels:
        app: api-gateway
        project: university-management
    spec:
      containers:
        - name: api-gateway
          image: us-central1-docker.pkg.dev/university-management-476414/university-management/api-gateway:latest
          ports:
            - containerPort: 9090

---

# Deployment for student-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-service
  labels:
    app: student-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-service
      project: university-management
  template:
    metadata:
      labels:
        app: student-service
        project: university-management
    spec:
      containers:
        - name: student-service
          image: us-central1-docker.pkg.dev/university-management-476414/university-management/student-service:latest
          ports:
            - containerPort: 8080

---

# Deployment for address-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: address-service
  labels:
    app: address-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: address-service
      project: university-management
  template:
    metadata:
      labels:
        app: address-service
        project: university-management
    spec:
      containers:
        - name: address-service
          image: us-central1-docker.pkg.dev/university-management-476414/university-management/address-service:latest
          ports:
            - containerPort: 8080
